# Generated by Django 2.2.12 on 2022-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msgs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('msg', models.CharField(default='', max_length=1000)),
                ('img', models.ImageField(default='', upload_to='../media/')),
            ],
        ),
    ]
