# Generated by Django 2.2.12 on 2022-07-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0002_auto_20220730_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgs',
            name='img',
            field=models.ImageField(default='', upload_to='media/static/'),
        ),
    ]
