# Generated by Django 2.2.12 on 2022-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0003_auto_20220730_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=255)),
                ('news', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='msgs',
            name='img',
            field=models.FileField(default='', upload_to='../media/media/static/'),
        ),
    ]
