# Generated by Django 2.2.12 on 2022-07-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0005_auto_20220730_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
