# Generated by Django 2.2.12 on 2022-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0006_auto_20220730_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
