# Generated by Django 2.2.12 on 2022-07-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0008_auto_20220730_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='', max_length=255)),
                ('course_category', models.CharField(default='', max_length=255)),
                ('date', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
