# Generated by Django 2.2.12 on 2022-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0009_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
