# Generated by Django 2.2.12 on 2022-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0010_courses_course_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
