# Generated by Django 2.2.12 on 2022-07-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0011_auto_20220730_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(default='', upload_to='../media/media/static')),
                ('date', models.DateField(default='')),
            ],
        ),
    ]
