# Generated by Django 2.2.12 on 2022-08-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0013_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=244)),
                ('appointment', models.CharField(default='', max_length=244)),
                ('desc', models.CharField(default='', max_length=2444)),
                ('contact', models.CharField(default='', max_length=255)),
                ('img', models.FileField(default='', upload_to='../media/media/static/')),
            ],
        ),
    ]
