# Generated by Django 4.1 on 2022-12-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0014_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=123)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='photo',
            field=models.FileField(default='', upload_to='../media/media/static'),
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='etc.category'),
        ),
    ]
