# Generated by Django 4.1 on 2022-12-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0016_remove_courses_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='photo',
        ),
    ]
