# Generated by Django 4.1 on 2022-12-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0020_alter_courses_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='img',
            field=models.FileField(default='', upload_to='media/media/static/'),
        ),
        migrations.AlterField(
            model_name='msgs',
            name='img',
            field=models.FileField(default='', upload_to='media/media/static/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(default='', upload_to='media/media/static'),
        ),
    ]
