# Generated by Django 4.1 on 2022-12-09 07:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etc', '0021_alter_faculty_img_alter_msgs_img_alter_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='msgs',
            name='msg',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
